name: Build & Temporary Release

on:
  push:
    branches:
      - main

env:
  WORKING_DIR: ./my-web-app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm install

      - name: Set up env
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          touch .env.production
          echo "VITE_BASE=${{ secrets.DEV_BASE || './' }}" >> .env.production
          echo "VITE_APP_NAME=${{ secrets.DEV_APP_NAME || 'EasyShop App' }}" >> .env.production
          echo "VITE_CORE_API_URL=${{ secrets.DEV_CORE_API_URL }}" >> .env.production

      - name: Build project
        working-directory: ${{ env.WORKING_DIR }}
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: "${{ env.WORKING_DIR }}/dist"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist
      - name: Assume Role
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_AWS_ROLE_ARN_KEY_NAME }}
          aws-region: "ap-southeast-1"
      - name: Run CloudFormation
        id: run-cloud-formation
        shell: bash
        run: |
          ls -l
          aws s3 ls
          aws s3 sync ./dist/ s3://app.grp6asm3.com --follow-symlinks --delete
